jobs:
  build:
    working_directory: ~/ethereumex
    docker:
      - image: elixir:latest

    steps:
      - checkout
      - run: wget https://releases.parity.io/v1.10.7/x86_64-unknown-linux-gnu/parity
      - run: chmod 755 ./parity
      - run: echo > passfile
      - run:
          name: "Parity"
          command: ./parity --chain dev
          background: true
      
      - restore_cache:
          keys:
            - v2-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
            - v2-dependency-cache-{{ arch }}
            - v2-dependency-cache

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix credo
      - run: mix format --check-formatted
      - run:
          command: mix compile
          environment:
            MIX_ENV: test

      - save_cache:
          key: v2-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

      - run: mix test --include eth --include batch

      - restore_cache:
          keys:
            - v2-plt-cache-{{ arch }}-{{ checksum "mix.lock" }}
            - v2-plt-cache-{{ arch }}
            - v2-plt-cache

      - run: mix dialyzer --plt

      - save_cache:
          key: v2-plt-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - ~/.mix

      - run: mix dialyzer --halt-exit-status
